### ISSUE TITLE
Document how this repository/plugin interacts with Rancher storage pools

### ISSUE THREAD

**Issue by ndarilek** [rancher/convoy#130]
This repo contains a plugin called Convoy, and a `convoy` binary for interacting with volumes created by it.

The Rancher catalog contains various Convoy storage drivers, which are independent of their underlying storage technology (I.e. there is a Gluster stack and a Convoy Gluster addon.)

I'd like to see some docs reconciling these concepts. To wit:

 * What is the connection between this volume plugin and the storage pool stacks of the same name? There are no instructions to install this plugin in the tutorial that shows how to launch a *Convoy* Gluster stack under Rancher.
 * Assuming these are the same technology, how would I use Convoy to snapshot a Gluster volume in the Convoy Gluster stack? The capability to do so is advertised, but there doesn't seem to be a way to do it since the storage is in the Docker container and not on the host.

As it stands these seem like different technologies, with the storage pool stacks incidentally named Convoy XXX, but they do apparently ship the convoy binary in them (albeit in a way that apparently doesn't work in terms of snapshotting.) I'd like to know how they work together, even if the answer is "they don't right now but we're working on it." I'd also like to know, when building a production-grade system where I want storage available everywhere, if I should spend time on the Convoy-branded stacks or just use this plugin.

Thanks.

**Comment by yasker** [comment]
1. Convoy is the base app for Rancher `convoy-nfs` or other `convoy`prefixed solutions.
2. Others are packaged as a template, which can be used to run `convoy` inside Rancher easily and use the volume function.
3. Convoy still can used to do snapshot/backup etc, but Rancher hasn't got that functionality yet. So yes, we're working on it.
4. Sadly, we don't have enough resource to maintain glusterfs, so that one has been pulled out of rancher catalog...

Our suggestion will be use template shipping with Rancher, and it will be improved. The progress in Convoy itself can be faster than the one used by Rancher though.
