### ISSUE TITLE
is there any working convoy-glusterfs configuration ?

### ISSUE THREAD

**Issue by derDieDasJojo** [rancher/convoy#142]
I dont get it.
I've been trying around for days with different version of convoy-gluster fs, different operating systems and different docker versions. but did not get ANY of them to work.
So does anyone have a working configuration of convoy glusterfs ? please post your configuration of:
os, docker-version, convoy-agent docker file version,... here

thanks

**Comment by deniseschannon** [comment]
I have had success with RancherOS v0.4.5, which comes with Docker 1.10.3 using the templates in the catalog.

**Comment by jeanlouisboudart** [comment]
i guess the real question was again and still how to make convoy-glusterfs work with docker 1.11 :)

**Comment by saphoooo** [comment]
I did. I made some changes in glusterfs catalog entry because of some constraints (only 2 bricks instead of 3), and deploy convoy-gluster from catalog. Everything work as expected.
Where do you run your glusterfs server? Is it an internal stack or is it an external services?
I'm running RancherOS v0.4.5 (Docker version 1.10.3, build 20f81dd)

**Comment by VAdamec** [comment]
In last version of Rancher there is no convoy-glusterfs at all, it's deprecated ?

**Comment by ksachdev1** [comment]
I am going to be experimenting with it today. Here is my docker version
docker --version
Docker version 1.12.5, build 047e51b/1.12.5

so from these posts, i feel it most likely won't work?

**Comment by derDieDasJojo** [comment]
it looks like they removed support for glusterfs
https://forums.rancher.com/t/glusterfs-not-available-in-catalog/4278/2
