### ISSUE TITLE
Is convoy still supported and actively being developed?

### ISSUE THREAD

**Issue by wzrdtales** [rancher/convoy#208]
Hey just quickly wanted to ask if convoy is still supported, developed or if it is being dropped in favour of https://github.com/rancher/storage?

I ask as we have a need for a persistent storage solution, but all current available ones are no option at all for us currently and we just setup a CEPH cluster which me most probably will go for, so I am looking at the projects that are still relevant, where I can add CEPH (specifically rbd) as a supported storage.

Thanks in advance.

**Comment by pgeorgiev333** [comment]
Same question from me. I see people talking about Rancher NFS and i'm not sure if it is this pluign or something else

**Comment by Ramblurr** [comment]
The fact that nearly a month can pass without a dev commenting as to whether this project is supported or actively maintained, says a lot I think.

**Comment by cjellick** [comment]
Sorry for the delayed response! Long story short: convoy is no longer being actively developed. We took the lessons we learned from it and applied them to github.com/rancher/storage. So, Rancher NFS, Rancher EBS, and Rancher EFS (and others in the future) are the successors to convoy and are being actively developed and maintained.

To your question about CEPH @wzrdtales: we've also enhanced storage setup in Rancher itself so that as long as you have a docker volume plugin, you can wire it into Rancher as a first class storage provider. So, if you have such a plugin for CEPH, you just need to create a "storage_service" following this as an example: https://github.com/rancher/rancher-catalog/blob/master/infra-templates/nfs/2/rancher-compose.yml#L38-L42

**Comment by cjellick** [comment]
Sorry for the delayed response! Long story short: convoy is no longer being actively developed. We took the lessons we learned from it and applied them to github.com/rancher/storage. So, Rancher NFS, Rancher EBS, and Rancher EFS (and others in the future) are the successors to convoy and are being actively developed and maintained.

To your question about CEPH @wzrdtales: we've also enhanced storage setup in Rancher itself so that as long as you have a docker volume plugin, you can wire it into Rancher as a first class storage provider. So, if you have such a plugin for CEPH, you just need to create a "storage_service" following this as an example: https://github.com/rancher/rancher-catalog/blob/master/infra-templates/nfs/2/rancher-compose.yml#L38-L42

**Comment by wzrdtales** [comment]
Luckily rexray as of today supports ceph, https://github.com/codedellemc/rexray#storage-provider-support

So just the current rax-ray which is quite outdated needs to be updated.

**Comment by yasker** [comment]
Need to clarify a bit here.

1. Convoy is still maintained and supported as a standalone volume plugin for Docker. We're still trying to address bug and answer questions. But as my colleague @cjellick said, we're not currently actively developing Convoy. It means we're not adding new major features and only deal with bug fixes at the moment.

2. Current rancher-storage is the new way to integrate with Rancher. Convoy will still serve as a standalone volume plugin for Docker, outside of Rancher scope.

3. Personally, I am really sorry we haven't spent enough time on Convoy recently. I was busy working on another project at the moment. I will continue working on Convoy whenever I have time.

**Comment by Ramblurr** [comment]
@yasker thanks for the reply. 

I've been looking at rancher/storage and trying to see if there is a comparable feature there to convoy's VFS/devicemapper storage feature. It seems that only EBS and NFS drivers exist at the moment.

For a small non-clustered docker/rancher deployment, would you still suggest using convoy's VFS/devicemapper features to create, manage, and backup volumes?

**Comment by yasker** [comment]
@Ramblurr For a single node, device mapper should still work fine, since you get the best snapshot/backup feature.

For more than one node, you need to take a look at mounted NFS with VFS driver.

**Comment by Ramblurr** [comment]
@yasker  Thanks. Do you recommend using the latest release or compiling from source?

**Comment by pgeorgiev333** [comment]
Hi. 
I looked at rancher/storage repo and the readme says:

> Running
> 
> Add this repo as a catalog in Rancher to run the local builds

How can i run/use this without Rancher (like we used to do with convoy)?

**Comment by yasker** [comment]
@pgeorgiev333 

For rancher/storage, you need to run it with Rancher. The option of without Rancher is not supported.

You still need to use Convoy if you don't have Rancher in the scope.

**Comment by pgeorgiev333** [comment]
Thanks. So i'll try longhorn someday as in my experience convoy does not work really well in swarm (the old swarm; have not tried the new swarm mode yet) with NFS (i get flock errors).
