### ISSUE TITLE
Recommended practice for backgrounding convoy daemon process?

### ISSUE THREAD

**Issue by prelegalwonder** [rancher/convoy#21]
I noticed that running convoy daemon does not background by default. What is the recommended way to do this? 

- nohup / background it (when not debugging)
- write an init script for it 
- dockerize it
- add a feature to run in background. 

Here's my command:
```
sudo convoy daemon --drivers vfs --driver-opts vfs.path=/mnt/nfs/Backup/docker
```
Am I missing anything?

**Comment by yasker** [comment]
Either `nohup` or init script(found one at https://github.com/fhd/init-script-template) would be fine.

We were working on dockerization, but found some problems with Docker to get things done well. Especially since it would work as a docker plugin, it would be in a loop dependency(e.g. docker need to load plugin, which need to run inside docker). So currently we don't recommend to run it in Docker.

So far we don't have plan to add support to run it in background automatically, since it's relatively easy to do that in various Linux ways. 

Seems `nohup` is the easiest way, and init script is needed when you want to start system with it.

**Comment by prelegalwonder** [comment]
Great, makes sense. Thank you for the clarification.

**Comment by deviantony** [comment]
Init script available here: https://gist.github.com/deviantony/557984d62e867e6f505577b207db6ffc
