### ISSUE TITLE
Convoy plugin repo for CentOS / Ubuntu / Arch / RancherOS

### ISSUE THREAD

**Issue by pwFoo** [rancher/convoy#24]
Is a convoy repo planned to install and update convoy plugin with the OS package manager?

RancherOS could ship it as os-service via ros.

**Comment by yasker** [comment]
Not yet. Package for every distribution would be quite some work, we're leaning toward a Docker container package. But currently there are some issues on Docker side to prevent us to provide the same level experiences in Docker container as we do static binary now, like Docker need to start plugin container before others containers depends on the plugin. So currently we're still shipping as static binary. Since there isn't much dependency for the static-linked binary, we found it's acceptable for now.

**Comment by pwFoo** [comment]
Hi @yasker 
static-linked binary is fine. Distribution packages could be fine because of updates and bug fixes. 

But it would be ok to be focused on RancherOS, which I like and testing with. ;)
So an os-service could be updated and the binary linked to RancherOS console container (that's the way RancherOS works? I'm not sure...) and is reboot save.

I opend an os-service request for RancherOS (#567), because it would help to work with persistent data.

**Comment by yasker** [comment]
Hi @pwFoo 

Working with distribution is more complex because:
1. We have to prepare for all mainstream Linux distros. Docker lists 11 distros it supports on it's website. And that's not included different versions of one distro.
2. We would want to dynamic linked binary if we want to do package distribution, since we suppose to know exactly the environment it would running on.

So in the future the more likely way we want to get Convoy distributed is in Docker container, after Docker solves their plugin containers issues.

And I'd like to have RancherOS with native Convoy support, but it depends on how RancherOS guys think about this...

**Comment by pwFoo** [comment]
Thanks @yasker. 
convoy as docker container would be the best solution. I hope it will be fixed soon.

Because of persistent volumes and also snapshot, backup and restore feature it would be great to be shipped with RancherOS. 

I like the way of RancherOS, but some features are missing and should be added as os-service (container). At the moment there is only debian-console and ubuntu-console, but no nice / needed additional system services or docker plugins.

**Comment by pwFoo** [comment]
Hi @yasker 
created a quick and dirty system-docker RancherOS convoy container.
http://forums.rancher.com/t/add-binary-to-rancheros-as-os-service/501/3

It works with system-docker and (user-)docker

**Comment by pwFoo** [comment]
Any progress with a RancherOS system-docker convoy container /service?

It's simple to install / use with OS like CentOS, but should be well integrated with RancherOS. Because volumes used with user-docker the docker plugin should run as system-docker?

Is there a convoy container available?

**Comment by pwFoo** [comment]
I just post a link to my RancherOS os-service workaround / first try:
https://github.com/rancher/os/issues/706#issuecomment-168434624

Would love to see a official os-service for RancherOS, but close this issue here.
