### ISSUE TITLE
Convoy DeviceMapper & RancherOS

### ISSUE THREAD

**Issue by pwFoo** [rancher/convoy#65]
RancherOS use the hole disk for local installation. How to set up RancherOS with convoy and devicemapper? WIll the [dm_dev_partition.sh](https://raw.githubusercontent.com/rancher/convoy/master/tools/dm_dev_partition.sh) work for that use case (if I resize the RancherOS partition to get some space and use /dev/sda2 for convoy DM)?

**Comment by yasker** [comment]
We haven't integrated RancherOS with Convoy yet...

`dm_dev_partition.sh` dealt with a whole disk(`/dev/sda` rather than `/dev/sda2`), because it will create partition table on it. So currently it's not possible to use it in that way. 

To use a partition rather than whole disk for device mapper, you will need to modify the partition table, which is more risky because it can corrupt current disk. I will prefer to do that manually.
